package com.zplus.ArtnStockMongoDB.controller;

import com.google.firebase.messaging.*;
import com.zplus.ArtnStockMongoDB.dto.req.MessageReq;
import com.zplus.ArtnStockMongoDB.model.NotificationMaster;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;


@RestController
public class MessagingController {

    @PostMapping("/send")
    public String sendMessage() {

//        NotificationMaster notificationMaster=new NotificationMaster();
//        notificationMaster=notificationMasterDao.findbyId(messageReq.getNotificationId()).get();

        Message message=Message.builder()
                .setNotification(Notification.builder()
                        .setBody(" devesh agaga")
                        .setTitle(" just for test ")
                        .build())
                        .setToken("eyJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImNsYWltcyI6eyJwcmVtaXVtQWNjb3VudCI6dHJ1ZX0sImV4cCI6MTcwODA3MDc1MSwiaWF0IjoxNzA4MDY3MTUxLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay0yY3RqeUBtZXNzYWdpbmctNTYzOGEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzdWIiOiJmaXJlYmFzZS1hZG1pbnNkay0yY3RqeUBtZXNzYWdpbmctNTYzOGEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJ1aWQiOiI2NWNmMDk0ZjQxMGZlMjIwYTM2NjRlZDUifQ.alsjy5s1zRkf7WTviGnOw6OL_vqkssXwnptHKQIyylSofD8FEua3Fy6C4_YpxGno9L-ogpEXF0H-jXm_GsDHAGvrF4PoHg4zoBcmGBxYpO8J4iQL_FVJCdYp-cWhji1Wxxb6a6xQ9rUyeOsLZI1h5FmECvYjiEhKKoMj1-36ih5CEM8o5SXUh3XIoCXJu5NKWvn5PoUHrApxgpKV3RTuyzmnHJaWrO3fHJVmk0BDgz3GhrLp3IcuIhhIEG3TE5LziIpTRH985bbrQHrURw_Kw3eaoDWLqSEoyXk9jKS9Cv6jN_kbqML2LrWw02JnVNzJan73g7Ele8KdieXw5mIX3A")
                        .build();
        try {
            FirebaseMessaging.getInstance().send(message);
            return "Message sent successfully!";
        } catch (Exception e) {
            return "Error sending message: " + e.getMessage();
        }
    }


    @PostMapping("/send-web-push")
    public String sendWebPushNotification() {
        WebpushConfig webpushConfig = WebpushConfig.builder()
                .setNotification(WebpushNotification.builder()
                        .setTitle("Title")
                        .setBody("Body")
                        .build())
                .putHeader("ttl", "300") // Time-to-live in seconds
                .build();

        try {
            FirebaseMessaging.getInstance().send(Message.builder()
                    .setWebpushConfig(webpushConfig)
                    .setToken("device_registration_token") // This should be the token generated by the browser
                    .build());
            return "Web push notification sent successfully!";
        } catch (Exception e) {
            return "Error sending web push notification: " + e.getMessage();
        }
    }
////        WebpushConfig webpushConfig = WebpushConfig.builder()
////                .setNotification(WebpushNotification.builder()
////                        .setTitle("Title")
////                        .setBody("Body")
////                        .build())
////                .putHeader("ttl", "300") // Time-to-live in seconds
////                .build();
//
//        try {
//            FirebaseMessaging.getInstance().send(Message.builder()
//                    .setWebpushConfig(webpushConfig)
//                                    .setNotification(Notification.builder().setTitle("")
//                                            .setBody("")
//                                            .build())
//                                    .setToken("")
//                                    .build());
//
//
//////                    .setNotification(new Notification("Title", "Body"))
////                    .setToken("device_registration_token") // This should be the token generated by the browser
////                    .build());
//            return "Web push notification sent successfully!";
//        } catch (Exception e) {
//            return "Error sending web push notification: " + e.getMessage();
//        }
//    }

}
